### ISSUE TITLE
Cross platform using Go

### ISSUE THREAD

**Issue by srs** [gdubw/gdub#20]
Just wanted to say that I have been using your project some time now and recently started to create a "bat" wrapper for windows. Since I totally suck at batch scripts in windows I decided to try to make it using Go.

Pushed it up on github (https://github.com/srs/gw) but do not want to create bad wibes so if you think creating this stuff in Go is the right thing (for better cross-platform support) then we could work on this toghether and I will donate the code to you. 

Just ping me and let me know what you think.

BR,
Sten Roger

**Comment by dougborg** [comment]
Hey Sten,

No bad vibes at all! This is great and I do like the go solution for better cross-platform compatibility better than having to maintain variants in different scripting languages for different platforms. I am actually moving to a new company that will prevent me from contributing much to OSS, so I am going to have to abandon gdub anyway. 

I don't have much (if any) real experience with go, but I would love to learn! I can help you get the go version of gw publishing some binaries and maybe running some tests.

**Comment by srs** [comment]
Congratulations on your new job and I am sorry to hear that you cannot contribute to the OSS that much anymore. You have been great at helping me in my pet projects so I will really miss your contributions there. 

Since you are going to abandon gdub it makes sense for me to work on the gw project (or rename to gdub if that's a more known name). Go is really great and I enjoy that a alot. I'm happy if you help out in anyway you can :-)

**Comment by dantesun** [comment]
Windows 10 has good support for Linux subsystem. Close for now.
