### ISSUE TITLE
Add support for finding gradle wrapper in master project in flat hierarchy

### ISSUE THREAD

**Issue by ki82** [gdubw/gdub#21]
If you are using a flat setup with the gradle wrapper defined in the master folder gw should be able to find the masters gradle wrapper if you in project1 or project2 type gw.

|-- project1
|-- project2
|-- master
   -- gradlew

"It looks in a directory called master which has the same nesting level as the current dir." from:
https://docs.gradle.org/current/userguide/userguide_single.html#customLayout

**Comment by dantesun** [comment]
https://github.com/gdubw/gng/releases/tag/v1.0.2 fixed this issue.
