### ISSUE TITLE
use installed gradle if major version is close

### ISSUE THREAD

**Issue by soloturn** [gdubw/gdub#37]
when on a rolling linux release, one always has a recent gradle version installed. it would be great if gw could use it if it is sufficiently close. e.g. major 6 is the same for installed and gradlew version than use local install.

**Comment by dantesun** [comment]
The version compatibility test should be done by Gradle and if you are stick to gradlew, you won't have any issue.

**Comment by dantesun** [comment]
1. Always stick to gradlew. 
2. use 'gng wrapper -v [version]' is a quick way upgrading your Gradle version.
