### ISSUE TITLE
Better detection of gradle build file names. 

### ISSUE THREAD

**Issue by dougborg** [gdubw/gdub#4]
Some projects don't use the default name of `build.gradle`. For a static case like this (all build files named the same thing) someone could just edit the script and change the value for `GRADLE_BUILDFILE`, but this isn't really convenient.

**Comment by dantesun** [comment]
If you don't specify the '-b' option, Gradle will discover the project to build automatically. So I remove the whole logic of determine the project directory by searching for a build.gradle[.kts] file.  And the latest code works in ratpack project.

@davidmc24 @dougborg I am closing this issue for now. Please reopen it if there's something I am missing.

**Comment by dantesun** [comment]
Reopen it since gng is not officially released yet.

**Comment by dantesun** [comment]
https://github.com/gdubw/gng/releases/tag/v1.0.2 fixed this issue.
